---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-ipfilter-test

resources:
- ns.yaml
- sfc.yaml
- client.yaml
- nse-ipfilter
- ../../apps/nse-kernel

patches:
- path: server-patch.yaml